[project]
name = "cypress-no-workie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.116.1",
    "itsdangerous>=2.2.0",
    "msal>=1.33.0",
    "uvicorn>=0.35.0",
]
